### ISSUE TITLE
Website problem

### ISSUE THREAD

**Issue by 3PSY0N** [Ionaru/easy-markdown-editor#538] opened 2023-03-22 13:43 UTC
You website is blocked by my antivirus

![image](https://user-images.githubusercontent.com/78256817/226922920-18f92224-be4a-4c91-87ec-29e6154a94ea.png)

**Comment by Ionaru** [comment] 2023-03-22 18:11
Duplicate of https://github.com/Ionaru/easy-markdown-editor/issues/526

**Closed by Ionaru** 2023-03-22 18:11 UTC
Labels: Bug
