### ISSUE TITLE
Broken demo in README

### ISSUE THREAD

**Issue by JulienPalard** [Ionaru/easy-markdown-editor#537] opened 2023-03-22 09:18 UTC
**Describe the bug**

Following the "Try the demo" link in the README file navigates to a "stolen" domain:

```
$ curl -i https://easy-markdown-editor.tk/
HTTP/1.1 302 Found
[...]
location: http://ww25.easy-markdown-editor.tk/?subid1=20230322-2015-49fa-ae39-217ca9d82ed9
[...]

$ curl -i 'http://ww25.easy-markdown-editor.tk/?subid1=20230322-2015-49fa-ae39-217ca9d82ed9'
HTTP/1.1 200 OK
[...]
Set-Cookie: parking_session=a3d20013-6286-b797-0ed4-553a81e6f4e5; expires=Wed, 22-Mar-2023 09:31:02 GMT; Max-Age=900; path=/; HttpOnly
[...]
<script>window.park = 
[...]
```

**Comment by Ionaru** [comment] 2023-03-22 18:11
Duplicate of https://github.com/Ionaru/easy-markdown-editor/issues/526

**Closed by Ionaru** 2023-03-22 18:11 UTC
Labels: Bug
