### ISSUE TITLE
Support for extending marked renderer

### ISSUE THREAD

**Issue by gseastream** [Ionaru/easy-markdown-editor#237] opened 2020-09-12 00:03 UTC
**Is your feature request related to a problem? Please describe.**
I'm relatively new to embedded markdown editors, but I think it would be really helpful to have support for extending the marked renderer to have custom renderers. For example, I'd love to be able to demote headers by 2 levels (so headers start at h3 in the preview), which can be done with the `marked.use` functionality, similar to the [example in their docs](https://marked.js.org/using_pro). I'd like this feature to be able to match the header demotion I'm doing with a Python-Markdown extension in the backend.

**Describe the solution you'd like**
This can be done with a new option for a `renderer` object that will specifically be used in the `marked.use` method. The rendered object need only contain the methods the user wishes to overwrite. I don't know if this would need to be reset between calls to the `markdown` method, especially if there's multiple instances of EasyMDEs with different renderers. But this functionality would unlock all sorts of extensible markdown filtering features.

**Describe alternatives you've considered**
I can't think of any other way to integrate this with marked. The only other thing I can think of is a custom parser for the `previewRender` option that changes the header tags manually, but this is far more complicated that simply being able to use the marked rendering method which passes the header level and the text for you.

**Additional context**
Thanks for maintaining this package! I migrated over here from SimpleMDE because of the mobile compatibility issues, but I'm happy to see how much has been added as well!

**Comment by Ionaru** [comment] 2020-09-13 20:28
Duplicate of #220

The default renderer can be changed by using the `previewRender``option. You can either replace it with an extended version of `marked` or use something else entirely.

**Closed by Ionaru** 2020-09-13 20:28 UTC
Labels: Duplicate, Feature
