### ISSUE TITLE
How to implement tribute.js?

### ISSUE THREAD

**Issue by artknight** [Ionaru/easy-markdown-editor#361] opened 2021-10-20 22:05 UTC
Hi,
I would love to add @mentions to my editor. Is there a way to implement tribute.js? or any other framework?

Thank you,
Art

**Comment by Ionaru** [comment] 2021-10-20 22:31
I don't think opening a second issue about the same subject is helpful, it's better to keep it all in one place.

Duplicate of #198.

**Closed by Ionaru** 2021-10-20 22:31 UTC
