### ISSUE TITLE
Split mode should be available in non full screen

### ISSUE THREAD

**Issue by damodharanj** [Ionaru/easy-markdown-editor#233] opened 2020-08-23 10:39 UTC
Split mode is available only in fullscreen. It should be available within the container too.

**Comment by nick-denry** [comment] 2020-08-25 19:21
Duplicate of https://github.com/Ionaru/easy-markdown-editor/issues/21 ?

**Comment by nick-denry** [comment] 2020-08-25 19:25
Try **sideBySideFullscreen** option. If set to `false`, allows side-by-side editing without going into fullscreen. Defaults to `true`.

**Closed** 2020-08-26 10:53 UTC
Labels: Feature
